export const ENEMIES = {
  scout_zero: {
    id: 'scout_zero',
    kind: 'fighter',
    hp: 1,
    speed: 1.9,
    score: 100,
    fireRate: 95,
    bulletSpeed: 3.1,
    animFps: 7,
    anim: ['zero_a', 'zero_b', 'zero_c'],
  },
  torpedo_gull: {
    id: 'torpedo_gull',
    kind: 'fighter',
    hp: 2,
    speed: 1.5,
    score: 100,
    fireRate: 88,
    bulletSpeed: 2.8,
    animFps: 6,
    anim: ['gull_a', 'gull_b', 'gull_c'],
  },
  canopy_raider: {
    id: 'canopy_raider',
    kind: 'fighter',
    hp: 5,
    speed: 2.1,
    score: 100,
    fireRate: 82,
    bulletSpeed: 3.2,
    animFps: 8,
    anim: ['raider_a', 'raider_b', 'raider_c'],
  },
  gunship_hornet: {
    id: 'gunship_hornet',
    kind: 'gunship',
    hp: 9,
    speed: 1.4,
    score: 250,
    fireRate: 66,
    bulletSpeed: 3.3,
    animFps: 5,
    anim: ['hornet_a', 'hornet_b', 'hornet_c'],
  },
  dune_lancer: {
    id: 'dune_lancer',
    kind: 'fighter',
    hp: 6,
    speed: 2.4,
    score: 100,
    fireRate: 74,
    bulletSpeed: 3.4,
    animFps: 8,
    anim: ['lancer_a', 'lancer_b', 'lancer_c'],
  },
  rail_bomber: {
    id: 'rail_bomber',
    kind: 'bomber',
    hp: 12,
    speed: 1.2,
    score: 250,
    fireRate: 58,
    bulletSpeed: 3,
    animFps: 5,
    anim: ['bomber_a', 'bomber_b', 'bomber_c'],
  },
  storm_wraith: {
    id: 'storm_wraith',
    kind: 'fighter',
    hp: 7,
    speed: 2.5,
    score: 100,
    fireRate: 64,
    bulletSpeed: 3.7,
    animFps: 8,
    anim: ['wraith_a', 'wraith_b', 'wraith_c'],
  },
  sub_spear: {
    id: 'sub_spear',
    kind: 'sub',
    hp: 14,
    speed: 0.8,
    score: 250,
    fireRate: 72,
    bulletSpeed: 2.8,
    animFps: 5,
    anim: ['sub_a', 'sub_b', 'sub_c'],
  },
};

export const MINI_BOSSES = {
  reef_guardian: {
    id: 'reef_guardian',
    hp: 40,
    speed: 0.7,
    score: 5000,
    fireRate: 40,
    bulletSpeed: 3.2,
    animFps: 5,
    anim: ['mb_reef_a', 'mb_reef_b', 'mb_reef_c'],
    drop: 'bomb-pack',
  },
  river_bastion: {
    id: 'river_bastion',
    hp: 120,
    speed: 0.65,
    score: 5000,
    fireRate: 36,
    bulletSpeed: 3.5,
    animFps: 5,
    anim: ['mb_river_a', 'mb_river_b', 'mb_river_c'],
    drop: 'shield',
  },
  convoy_ram: {
    id: 'convoy_ram',
    hp: 140,
    speed: 0.8,
    score: 5000,
    fireRate: 34,
    bulletSpeed: 3.6,
    animFps: 5,
    anim: ['mb_convoy_a', 'mb_convoy_b', 'mb_convoy_c'],
    drop: 'repair',
  },
  monsoon_blade: {
    id: 'monsoon_blade',
    hp: 155,
    speed: 1.0,
    score: 5000,
    fireRate: 32,
    bulletSpeed: 3.9,
    animFps: 6,
    anim: ['mb_monsoon_a', 'mb_monsoon_b', 'mb_monsoon_c'],
    drop: 'double-shot',
  },
};

export const FINAL_BOSSES = {
  coral_dreadnought: {
    id: 'coral_dreadnought',
    hp: 280,
    speed: 0.55,
    score: 25000,
    fireRate: 24,
    bulletSpeed: 4,
    animFps: 5,
    anim: ['fb_coral_a', 'fb_coral_b', 'fb_coral_c', 'fb_coral_d'],
    drop: 'double-shot',
  },
  jungle_citadel: {
    id: 'jungle_citadel',
    hp: 320,
    speed: 0.6,
    score: 25000,
    fireRate: 22,
    bulletSpeed: 4.1,
    animFps: 5,
    anim: ['fb_jungle_a', 'fb_jungle_b', 'fb_jungle_c', 'fb_jungle_d'],
    drop: 'speed-boost',
  },
  dust_colossus: {
    id: 'dust_colossus',
    hp: 360,
    speed: 0.66,
    score: 25000,
    fireRate: 21,
    bulletSpeed: 4.3,
    animFps: 5,
    anim: ['fb_dust_a', 'fb_dust_b', 'fb_dust_c', 'fb_dust_d'],
    drop: 'shield',
  },
  iron_tempest: {
    id: 'iron_tempest',
    hp: 420,
    speed: 0.72,
    score: 25000,
    fireRate: 19,
    bulletSpeed: 4.5,
    animFps: 6,
    anim: ['fb_iron_a', 'fb_iron_b', 'fb_iron_c', 'fb_iron_d'],
    drop: 'repair',
  },
};
